- obs space:
    <<: *ObsSpace
    name: AodCRTM
    _obsdatain: &ObsDataIn
      engine:
        type: H5File
        obsfile: {{InDBDir}}/aeronet_l15_aod_obs_{{thisValidDate}}.h5
        missing file action: warn
    _obsdataout: &ObsDataOut
      engine:
        type: H5File
        obsfile: {{OutDBDir}}{{MemberDir}}/{{obsPrefix}}_aeronet_l15_aod{{ObsOutSuffix}}.h5
    obsdatain:
      <<: *{{ObsDataIn}}
    {{ObsDataOut}}
    simulated variables: [aerosolOpticalDepth]
    channels: 1-8
  obs error: *ObsErrorDiagonal
  <<: *horizObsLoc
  obs operator:
    <<: *aodCRTMObsOperator
    obs options:
      <<: *AODCRTMObsOptions
      Sensor_ID: v.aeronet
