#!/usr/bin/env python3

'''
 (C) Copyright 2023 UCAR

 This software is licensed under the terms of the Apache Licence Version 2.0
 which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
'''

from initialize.config.Component import Component
from initialize.config.Config import Config
from initialize.config.Resource import Resource
from initialize.config.Task import TaskLookup
from initialize.data.Model import Mesh
from initialize.framework.HPC import HPC


class Emissions(Component):
  """Optional workflow-native preparation of GOCART2G emission inputs.

  The default ``prebuilt`` mode preserves the existing MPAS-Workflow behavior:
  Forecast.csh links files directly from Build.EmissionDir and no new Cylc task
  is added.

  In ``workflow`` mode a PrepareEmissions task runs immediately before each
  Forecast.  The task first mirrors the prebuilt emission directory, then may
  replace selected inventories with files generated by tools/mpas_emissions.
  This allows selected inventories to be regenerated while others remain prebuilt.
  """

  defaults = 'scenarios/defaults/emissions.yaml'
  workDir = 'Emissions'

  variablesWithDefaults = {
    # prebuilt: preserve existing static EmissionDir behavior
    # workflow: create an experiment-local emission directory before Forecast
    'mode': ['prebuilt', str, ['prebuilt', 'workflow']],

    # Workflow-native products: mesh, cams-anth, cams-biog, finn, ceds, gfas, qfed.
    # The default remains mesh-only and is inactive unless mode=workflow.
    'prepare': [['mesh'], list],

    # Transitional compatibility.  When true, mirror the legacy prebuilt
    # EmissionDir/PRMAreaDir before replacing selected products.  Set false for
    # a fully source-first experiment after every selected inventory is raw-driven.
    'seed prebuilt': [True, bool],

    # Runtime Python environment. The default uses MPAS-Workflow's NPL Python;
    # users who need to generate new ESMF weights can point the environment
    # script or python executable at an ESMPy-enabled environment.
    'environment script': ['config/environmentEmissions.csh', str],
    'python executable': ['python3', str],

    # Experiment-relative output/cache directories. {{mesh}} and {{nCells}} are
    # expanded by this component.
    'work directory': ['Emissions/{{mesh}}', str],
    'cache directory': ['Emissions/cache/{{mesh}}', str],

    # Optional explicit MPAS mesh/static file. Empty => use invariant-stream file.
    'mesh file': ['', str],

    # CAMS configuration supplies the source/species settings.  Any destination
    # SCRIP/weight paths in the YAML are ignored; MPAS-Workflow derives/caches
    # them from the active MPAS mesh.
    'cams anth config': ['', str],
    'cams biog config': ['', str],
    # Optional pre-existing validated weight file. Useful during migration for
    # x1.163842; leave empty for automatic mesh-specific generation/cache.
    'cams anth weights file': ['', str],
    'cams biog weights file': ['', str],
    'cams chunk links': [2000000, int],
    'cams conservation tolerance': [5.0e-5, float],

    # FINN configuration supplies source and species settings. The processor
    # overrides mpas_grid_file and dst_file_dir from workflow state.
    'finn config': ['', str],

    # PRM source is independent of the selected biomass-emission inventory.
    # 'finn' (recommended/default) uses FINN each-fire AREA statistics for all
    # FINN/GFAS/QFED members; 'prebuilt' uses Build.PRMAreaDir/File.
    'prm source': ['finn', str, ['finn', 'prebuilt']],

    # Regional point assignment.  For regional MPAS meshes, reject fires too far
    # from any valid cell rather than dumping them onto a boundary cell.
    'finn reject outside': [False, bool],
    'finn interior only': [False, bool],
    'finn max distance factor': [2.5, float],

    # Config-driven regular-grid inventories.  Source-specific details are
    # intentionally kept in YAML; the Python engine is shared by CEDS/GFAS/QFED.
    'ceds config': ['', str],
    'ceds weights file': ['', str],
    'gfas config': ['', str],
    'gfas weights file': ['', str],
    'qfed config': ['', str],
    'qfed weights file': ['', str],
    'regular chunk links': [2000000, int],
    'regular conservation tolerance': [5.0e-5, float],

    # If true, existing generated files are retained and preparation is cheap.
    'reuse existing': [True, bool],
  }

  def __init__(self, config:Config, hpc:HPC, mesh:Mesh):
    super().__init__(config)
    self.mesh = mesh

    self._set('emissionsMode', self['mode'])
    self._set('emissionsGridName', f'x{mesh.meshRatio}.{mesh.nCells}')
    self._set('emissionsEnvironmentScript', self['environment script'])
    self._set('emissionsPython', self['python executable'])
    self._set('emissionsPrepare', self['prepare'])
    self._set('emissionsSeedPrebuilt', self['seed prebuilt'])
    prepare = [str(v).lower() for v in self['prepare']]
    self._set('emissionsPrepareMesh', 'mesh' in prepare)
    self._set('emissionsPrepareFinn', 'finn' in prepare)
    self._set('emissionsPrepareCamsAnth', 'cams-anth' in prepare or 'cams' in prepare)
    self._set('emissionsPrepareCamsBiog', 'cams-biog' in prepare or 'cams' in prepare)
    self._set('emissionsPrepareCeds', 'ceds' in prepare)
    self._set('emissionsPrepareGfas', 'gfas' in prepare)
    self._set('emissionsPrepareQfed', 'qfed' in prepare)
    self._set('emissionsCamsAnthConfig', self['cams anth config'])
    self._set('emissionsCamsBiogConfig', self['cams biog config'])
    self._set('emissionsCamsAnthWeightsFile', self['cams anth weights file'])
    self._set('emissionsCamsBiogWeightsFile', self['cams biog weights file'])
    self._set('emissionsCamsChunkLinks', self['cams chunk links'])
    self._set('emissionsCamsConservationTolerance', self['cams conservation tolerance'])
    self._set('emissionsMeshFile', self['mesh file'])
    self._set('emissionsFinnConfig', self['finn config'])
    self._set('emissionsPrmSource', self['prm source'])
    self._set('emissionsFinnRejectOutside', self['finn reject outside'])
    self._set('emissionsFinnInteriorOnly', self['finn interior only'])
    self._set('emissionsFinnMaxDistanceFactor', self['finn max distance factor'])
    self._set('emissionsCedsConfig', self['ceds config'])
    self._set('emissionsCedsWeightsFile', self['ceds weights file'])
    self._set('emissionsGfasConfig', self['gfas config'])
    self._set('emissionsGfasWeightsFile', self['gfas weights file'])
    self._set('emissionsQfedConfig', self['qfed config'])
    self._set('emissionsQfedWeightsFile', self['qfed weights file'])
    self._set('emissionsRegularChunkLinks', self['regular chunk links'])
    self._set('emissionsRegularConservationTolerance', self['regular conservation tolerance'])
    self._set('emissionsReuseExisting', self['reuse existing'])

    work = self['work directory'].replace('{{mesh}}', mesh.name).replace('{{nCells}}', str(mesh.nCells))
    cache = self['cache directory'].replace('{{mesh}}', mesh.name).replace('{{nCells}}', str(mesh.nCells))
    self._set('EmissionsWorkDir', work)
    self._set('EmissionsCacheDir', cache)

    self.ready = None

    if self['mode'] == 'workflow':
      self.ready = 'PrepareEmissions'
      attr = {
        'seconds': {'def': 1800, 'typ': int},
        'nodes': {'def': 1, 'typ': int},
        'PEPerNode': {'def': 8, 'typ': int},
        'memory': {'def': '64GB', 'typ': str},
        'queue': {'def': hpc['SharedQueue']},
        'account': {'def': hpc['CriticalAccount']},
        'email': {'def': True, 'typ': bool},
      }
      job = Resource(self._conf, attr, ('job',))
      task = TaskLookup[hpc.system](job)
      self._tasks += ['''
  [[PrepareEmissions]]
    inherit = SingleBatch
    script = $origin/bin/PrepareEmissions.csh
'''+task.job()+task.directives()]

    self._cshVars = list(self._vtable.keys())
