  obs filters:
  - filter: PreQC
    maxvalue: 1
  - filter: Domain Check
    where:
    - variable:
        name: latitude@MetaData
      minvalue: -60
      maxvalue: 60
  - filter: Bounds Check
    filter variables:
    - name: aerosolOpticalDepth
      channels: 8 # 550 nm among 18 channels
    minvalue: 0
    maxvalue: 4.9
    action:
      name: reject
  - filter: Background Check
    channels: 8 # 550nm among 18 channel
    threshold: 3.0
    action:
      name: inflate error
      inflation factor: 3.0
  - filter: Gaussian Thinning
    horizontal_mesh: {{RADTHINDISTANCE}}
    action:
      name: reduce obs space
  - filter: RejectList
    defer to post: true
    filter variables:
    - name: aerosolOpticalDepth
      channels: 8 # 550 nm among 18 channels
