- obs space:
    <<: *ObsSpace
    name: AodCRTM
    _obsdatain: &ObsDataIn
      engine:
        type: H5File
        obsfile: {{InDBDir}}/harp2_fmapol_pace_aod_obs_{{thisValidDate}}.h5
    _obsdataout: &ObsDataOut
      engine:
        type: H5File
        obsfile: {{OutDBDir}}{{MemberDir}}/{{obsPrefix}}_harp2_fmapol_pace_aod{{ObsOutSuffix}}.h5
    obsdatain:
      <<: *{{ObsDataIn}}
    {{ObsDataOut}}
    simulated variables: [aerosolOpticalDepth]
    channels: 1-4 # 550 nm among 4 channels
  obs error: *ObsErrorDiagonal
  <<: *horizObsLoc
  obs operator:
    <<: *aodCRTMObsOperator
    obs options:
      <<: *AODCRTMObsOptions
      Sensor_ID: v.harp2_fmapol
