# HofX override of da/base/spexone_fmapol_pace_aod.yaml: identical except for the channel list
- obs space:
    <<: *ObsSpace
    name: AodCRTM
    _obsdatain: &ObsDataIn
      engine:
        type: H5File
        obsfile: {{InDBDir}}/spexone_fmapol_pace_aod_obs_{{thisValidDate}}.h5
        missing file action: warn
    _obsdataout: &ObsDataOut
      engine:
        type: H5File
        obsfile: {{OutDBDir}}{{MemberDir}}/{{obsPrefix}}_spexone_fmapol_pace_aod{{ObsOutSuffix}}.h5
    obsdatain:
      <<: *{{ObsDataIn}}
    {{ObsDataOut}}
    simulated variables: [aerosolOpticalDepth]
    channels: 1-34 # all 34 channels for verification (DA uses 7,22,32)
  obs error: *ObsErrorDiagonal
  <<: *horizObsLoc
  obs operator:
    <<: *aodCRTMObsOperator
    obs options:
      <<: *AODCRTMObsOptions
      Sensor_ID: v.spexone_fmapol
