- obs space:
    <<: *ObsSpace
    name: AodCRTM
    _obsdatain: &ObsDataIn
      engine:
        type: H5File
        obsfile: {{InDBDir}}/spexone_fmapol_pace_aod_obs_{{thisValidDate}}.h5
    _obsdataout: &ObsDataOut
      engine:
        type: H5File
        obsfile: {{OutDBDir}}{{MemberDir}}/{{obsPrefix}}_spexone_fmapol_pace_aod{{ObsOutSuffix}}.h5
    obsdatain:
      <<: *{{ObsDataIn}}
    {{ObsDataOut}}
    simulated variables: [aerosolOpticalDepth]
    channels: 1-34 # 548nm (closest to 550 nm) among 34 channels
  obs error: *ObsErrorDiagonal
  <<: *horizObsLoc
  obs operator:
    <<: *aodCRTMObsOperator
    obs options:
      <<: *AODCRTMObsOptions
      Sensor_ID: v.spexone_fmapol
